In [97]:
def f(x):
    value = 2*x+1 # one tab
    return value

result = f(1) # pass 3 to bind with result
print(result)

3


In [96]:
def f(x):
    value = 2*x+1 # one tab

result = f(1) # pass 3 to bind with result
print(result)

None


# change under the hood

In [95]:
def changeFirstToZero(x):
    x[0]=0

In [42]:
xx=[-3, 1, 4]
changeFirstToZero(xx) # x = xx

xx

[0, 1, 4]

In [46]:
# Lambda Function
f=lambda x:x+1
f(1)

2

In [47]:
# Lambda Function
f=lambda x,y:x+y
f(1,2) 

3

In [52]:
consumer = {
    'name': 'John Doe',
    'age': 30,
    'preference': lambda x,y: x**0.8*y**0.2
}

In [58]:

def Cobb_Douglas(alpha):
    def cd(x, y):
        return x**alpha*y**(1-alpha)
    return cd
# Cobb-Douglas constructor
cd = Cobb_Douglas(0.3)

cd(1, 2), cd(3,7)

(1.624504792712471, 5.428814526898253)

In [43]:
def CESutilityfunction(sigma, alpha):
    def CES(x,y):
        return (alpha*x**(-sigma)+(1-alpha)*y**
(-sigma))**(-1/sigma)
    return CES

CES=CESutilityfunction(0.5, 0.7)
CES(10,20)

12.01944966047974

In [88]:
class CES:
    def __init__(self, sigma, alpha):
        self.sigma=sigma
        self.alpha=alpha
    def utility(self, x, y):
        return (self.alpha*x**(-self.sigma)+(1-self.alpha)*y**(-self.sigma))**(-1/self.sigma)
    
ces=CES(0.5, 0.7)
ces.utility(10, 20)

12.01944966047974

In [1]:
import numpy as np

x = np.array([1, 2, 3])
sigma = 0.5
alpha = 0.7, 0.2, 0.1

x**(-sigma)*alpha # ** and * are elementwise operations
sum(x**(-sigma)*alpha)

0.8991563831562721

In [4]:
import numpy as np

x = np.array([1, 2, 3])
sigma = 0.5
alpha = 0.7, 0.2, 0.1

result=x**(-sigma)*alpha # ** and * are elementwise operations
result.sum()

0.8991563831562721

In [6]:
import numpy as np
class CESingeneral:
    def __init__(self, sigma, alpha):
        self.sigma=sigma
        self.alpha=alpha
    def utility(self, x):
        result=self.alpha*x**(-self.sigma)
        return (result.sum())**((-1)/self.sigma)

sigma=0.5
alpha=np.array([0.7, 0.2, 0.1])
cesg=CESingeneral(sigma,alpha)
x=np.array([1,2,3])
cesg.utility(x)

1.2368856089900797

In [93]:
import numpy as np
x=np.array([1,2,3])
y=np.array([1,2,3])

result=x*y
print(result)
sum=result.sum()
print(sum)

[1 4 9]
14


In [3]:
# Derivative constructor
def derivative(f, x, h=0.00001):
    return (f(x+h)-f(x))/h
def f(x):
    return x**2

derivative(f, 1, 1e-6), derivative(f,2)

(2.0000009999243673, 4.000010000027032)

In [4]:
def Derivative(f):
    def df(x, h=0.00001):
        return (f(x+h)-f(x))/h
    return df
df = Derivative(f)
df(1, 1e-5), df(2) 

(2.00001000001393, 4.000010000027032)

In [20]:
# gradient

def f(x):
    return x[0]**2*x[1]

def gradient(f, x, h=0.00001):
    x0 = x.copy()
    x0[0] += h # += is equivalent to x0[0] = x0[0] + h but more efficient
    x1 = x.copy()
    x1[1] += h
    return np.array([(f(x0)-f(x))/h, (f(x1)-f(x))/h])

gradient(f, [1, 2], 1e-6), gradient(f, [8, 2])

(array([4.000002, 1.      ]), array([32.00002, 64.     ]))

In [16]:
# Gradient Practice
import numpy as np
def f(x0,x1):
    return (x0**2)*x1
def df(x0,x1):
    h=1e-6
    return np.array([(f(x0+h,x1)-f(x0,x1))/h, (f(x0,x1+h)-f(x0,x1))/h])    

f(3,4), df(3,4)

(36, array([24.000004,  9.      ]))

In [1]:
import numpy as np
from numpy.linalg import inv
def qd(pd):
    qd=np.array((D@pd)+h)
    return qd
def qs(ps):
    qs=np.array((C@ps)+e)
    return qs  
def compute_equilibrium_price(D, h, C, e):
    data1=h-e
    data2=C-D
    data3=inv(data2)
    pe=data3@data1
    return pe

D=np.array([
    [-10,-5],
    [-1,-10]
])
h=np.array([
    [100],
    [50]
])
C=np.array([
    [10,5],
    [5,10]
])
e=np.array([
    [0],
    [0]
])

pe=compute_equilibrium_price(D, h, C, e)
compute_equilibrium_price(D, h, C, e), qd(pe), qs(pe)


(array([[4.41176471],
        [1.17647059]]),
 array([[50.        ],
        [33.82352941]]),
 array([[50.        ],
        [33.82352941]]))

In [94]:
import py.olg2 as olg  
ce = olg.consumer_example() 

ce["beta"], ce["u"](1.2)


(0.96, 0.1823215567939546)

In [1]:
import numpy as np
from numpy.linalg import inv
class Demand:
    def __init__(self, D, h):
        self.D=D
        self.h=h
    def quantity(self, pd):
        qd=np.array((self.D@pd)+self.h)
        return qd
class Supply:
    def __init__(self, C, e):
        self.C=C
        self.e=e
    def quantity(self, ps):
        qs=np.array((self.C@ps)+self.e)
        return qs 
class Market:
    def __init__(self, demand, supply):
        self.demand=demand
        self.supply=supply
    def price(self):
        pe=inv(C-D)@(h-e)
        return pe
    def quantity(self):
        qe=D@self.price()+h
        return qe

D=np.array([
    [-10,-5],
    [-1,-10]
])
h=np.array([
    [100],
    [50]
])
C=np.array([
    [10,5],
    [5,10]
])
e=np.array([
    [0],
    [0]
])

demand = Demand(D, h)
supply = Supply(C, e)
market = Market(demand, supply)

market.price(), market.quantity(), demand.quantity([[2],[4]]), supply.quantity([[1],[3]])

(array([[4.41176471],
        [1.17647059]]),
 array([[50.        ],
        [33.82352941]]),
 array([[60],
        [ 8]]),
 array([[25],
        [35]]))