In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
class Consumer_LogUtility:
    def __init__(self, beta):
        self.beta = beta
    def foc_c(self, knext: float, w: float, R: float): # (23.6b)
        """
        First order condition of the consumer's problem
        (knext, w, R)
        """
        return knext - (self.beta/(1+self.beta))*w

class Producer_cobbDouglas:
    def __init__(self, alpha):
        self.alpha = alpha
    def foc_l(self, k, w, l=1): # (23.9)
        """ 
        FOC with respect to labor
        (k, l, w)
        """
        return (1-self.alpha)*(k/l)**self.alpha - w
    def foc_k(self, k, R, l=1): # (23.9)
        """
        FOC with respect to capital
        (k, l, R)
        """
        return self.alpha*(l/k)**(1-self.alpha) - R

class OLGMarket:
    def __init__(self, consumer, producer, k0):
        self.consumer = consumer # composite 1
        self.producer = producer # composite 2
        self.k0 = k0
        self.k = k0
        self.equilibrium_dynamics = [[k0, None, None]]
    def generate_onePeriod_equilibrium(self):
        """
        return a tuple of (knext, w, R)
        and track the dynamics in self.equilibrium_dynamics
        """ # docstring: documentation string
        
        alpha = self.producer.alpha
        beta = self.consumer.beta

        w = (1-alpha)*self.k**alpha
        R = alpha*(self.k)**(alpha-1)
        knext = (beta/(1+beta))*w

        # keep track of the dynamics
        self.equilibrium_dynamics[len(self.equilibrium_dynamics)-1][1] = w
        self.equilibrium_dynamics[len(self.equilibrium_dynamics)-1][2] = R
        self.equilibrium_dynamics.append([knext, None, None])

        # set the market time to the next period
        self.k = knext
        return (knext, w, R)
    
    def clear_equilibrium_dynamics(self):
        self.equilibrium_dynamics = [[self.k0, None, None]]
        self.k = self.k0

In [26]:
def test(*args, epsilon):
    print(args)
    print(epsilon)

test(1,2,3, epsilon="Hi")

(1, 2, 3)
Hi


In [7]:
import numpy as np

def CESUtility(*alpha, rho):
    def ces(*x):
        x = np.array(x)
        return sum(x**(rho) * alpha)**(1/rho)
    return ces

u = CESUtility(0.3, 0.3, 0.4, rho=2)
u(2,4,5)

4.0

In [24]:
import numpy as np
def CESUtility(*alpha, rho):
    def function(*X):
        X=np.array(X)
        result=sum(alpha*X**rho)**(1/rho) 
        return result
    return function

# example 1
u = CESUtility(0.3, 0.3, 0.4, rho=2)
u(2,4,5)

4.0

In [35]:
# example 2
u2 = CESUtility(0.2, 0.2, 0.3, 0.3, rho=2)
u(1, 2, 2, 1)

In [ ]:
for x in X:
            value=(sum(a*x**(rho)))**(1/rho)
        return value
    return CESUtility(*X)

# Exercise Simulate Supply Shock process

In [7]:
import numpy as np
from numpy.linalg import inv
class Demand:
    def __init__(self, D, h):
        self.D=D
        self.h=h
    def quantity(self, pd):
        qd=np.array((self.D@pd)+self.h)
        return qd
class Supply:
    def __init__(self, C, e):
        self.C=C
        self.e=e
    def quantity(self, ps):
        qs=np.array((self.C@ps)+self.e)
        return qs 
class Market:
    def __init__(self, demand, supply):
        self.demand=demand
        self.supply=supply
    def price(self):
        pe=inv(self.supply.C-self.demand.D)@(self.demand.h-self.supply.e)
        return pe
    def quantity(self):
        qe=self.demand.D@self.price()+self.demand.h
        return qe
    def equilibrium(self):
        pe=self.price()
        qe=self.quantity()
        return pe, qe


D=np.array([
    [-10,-5],
    [-1,-10]
])
h=np.array([
    [100],
    [50]
])
C=np.array([
    [10,5],
    [5,10]
])
e=np.array([
    [0],
    [0]
])

demand = Demand(D, h)
supply = Supply(C, e)
market = Market(demand, supply)


market.equilibrium()

(array([[4.41176471],
        [1.17647059]]),
 array([[50.        ],
        [33.82352941]]))

In [8]:
# create supply shocks
import numpy as np
np.random.seed(2023)

epsilon = np.random.normal(0, 0.2, (10,2))

epsilon

array([[ 0.14233471, -0.06489699],
       [-0.20037413,  0.04725016],
       [-0.02043197, -0.22825853],
       [ 0.53088145,  0.28812104],
       [ 0.01978045, -0.62430643],
       [-0.21530433, -0.06513639],
       [-0.20709958, -0.08526408],
       [-0.20587228, -0.10435484],
       [-0.08455151, -0.01984883],
       [-0.2760516 ,  0.06038056]])

In [20]:
# create supply shocks
import numpy as np
np.random.seed(2023)

epsilon = np.random.normal(0, 0.2, (10,2))

import numpy as np
class AR:
    def __init__(self, epsilon, E0):
        self.epsilon = epsilon
        self.E0 = np.array(E0)
        self.memory = np.array([])
        self.EPast = np.array(self.E0)
    def simulate_nShocks(self, n=1):
        simulate_nShocks(self, n)
    def clear_memory(self):
        self.memory = np.array([])

# helpers

def simulate_oneShock(ar):
    # Simulate one shock of ar process
    for e in range(n):
        _ = market.supply.e
        y_oneShock_ahead = market.equilibrium()

    # Update EPast
    ar.EPast = np.append(y_oneShock_ahead, ar.EPast[:-1])

    ## append the new element to the memory
    ar.memory = np.append(ar.memory, y_oneShock_ahead)

def simulate_nShocks(ar, n):
    eps = ar.epsilon(n)
    for i in range(epsilon):
        simulate_oneShock(ar, eps[i])

ar=AR(epsilon=epsilon, E0=market.supply.e)

In [21]:
simulate_oneShock(ar)
ar.memory

NameError: name 'n' is not defined

In [30]:
simulate_nShocks(ar, 10)

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
import numpy as np

def Epsilon(mu, sigma):
    def draw(size):
        return np.random.normal(mu, sigma, size)
    return draw
epsilon = Epsilon(0, 1)    
enew=epsilon(10)
print(enew)